services:
  apip:
    build:
      context: ./apip
    volumes:
      - ./data:/data
    ports:
      - "8000:8000"
    environment:
      - DATA_PATH=/data
      - TTS_IP=tts
      - TTS_PORT=8001
      - GEMINI_IP=gemini
      - GEMINI_PORT=8002
      - API_PORT=8000

  tts:
    build:
      context: ./tts
    volumes:
      - ./data:/data
    ports:
      - "8001:8001"
    environment:
      - DATA_PATH=/data

  gemini:
    build:
      context: ./gemini
    volumes:
      - ./data:/data
      - ./google-key.json:/credentials.json
    ports:
      - "8002:8002"
    environment:
      - DATA_PATH=/data
      - GOOGLE_APPLICATION_CREDENTIALS=/credentials.json

  web:
    build:
      context: ./web
    volumes:
      - ./data:/data
    ports:
      - "8003:8003"
    environment:
      - DATA_PATH=/data
      - API_URL=http://apip:8000

volumes:
  data:
    driver: local