version: '3.8'

services:
  apip:
    build:
      context: ./apip
    volumes:
      - data:/data
    ports:
      - "8000:8000"
    environment:
      - DATAPATH=/data

  tts:
    build:
      context: ./tts
    volumes:
      - data:/data
    ports:
      - "8001:8001"
    environment:
      - DATAPATH=/data
      - APIP_URL=http://apip:8000

  gemini:
    build:
      context: ./gemini
    volumes:
      - data:/data
    ports:
      - "8002:8002"
    environment:
      - DATAPATH=/data
      - APIP_URL=http://apip:8000

  web:
    build:
      context: ./web
    volumes:
      - data:/data
    ports:
      - "8003:8003"
    environment:
      - DATAPATH=/data
      - APIP_URL=http://apip:8000

volumes:
  data:
    driver: local
