name: podai
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  firebase_auth: ^5.1.1
  firebase_core: ^3.1.1
  firebase_database: ^11.0.3
  firebase_storage: ^12.1.1
  cloud_firestore: ^5.1.0
  flutter:
    sdk: flutter
  google_sign_in: ^6.2.1
  http: ^1.2.2
  just_audio: ^0.9.28
  rxdart: ^0.27.5
  shared_preferences: ^2.0.6
  cached_network_image: ^3.2.0
  dio: ^4.0.0
  path_provider: ^2.0.0
  flutter_spinkit: ^5.1.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  share: ^2.0.4
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/audio/
    - assets/images/covers/
    - assets/images/profile/
